### ISSUE TITLE
Data Wrangling

### ISSUE THREAD

**Issue by ETGrif** [Shivthegod/ClassPrediction#5]
The data should be represented as a nested Series. The Upper Series holds each student, and each lower series holds the state of a student at each timestep. This is a cumulative view of when a student registers for a class. If no classes are registered for a timestep, the state should repeat.

**Comment by ETGrif** [comment]
For non-cumulative data, empty string, for cumulative. Just repeat the state

**Comment by ETGrif** [comment]
Deal with students that start before the start line of data

**Comment by ETGrif** [comment]
Plz make functions to pull a dict of classes and states for a given time step

**Comment by shivghosh** [comment]
Added and pushed
